// deepseek-prompt-lab/src/components/MessageComposer.tsx
import {
  DndContext,
  KeyboardSensor,
  PointerSensor,
  closestCenter,
  useSensor,
  useSensors,
  type DragEndEvent,
} from '@dnd-kit/core';
import { SortableContext, sortableKeyboardCoordinates, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { Plus } from 'lucide-react';
import type { ChatMessage } from '../domain/chat';
import { addMessage, copyMessage, moveMessage, removeMessage } from '../domain/messages';
import { MessageRow } from './MessageRow';

interface MessageComposerProps {
  messages: ChatMessage[];
  onChange: (messages: ChatMessage[]) => void;
  macroName: string;
  macroValue: string;
  onMacroValueChange: (value: string) => void;
}

export function MessageComposer({ messages, onChange, macroName, macroValue, onMacroValueChange }: MessageComposerProps) {
  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 6 } }),
    useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }),
  );

  const onDragEnd = ({ active, over }: DragEndEvent) => {
    if (!over || active.id === over.id) return;
    onChange(moveMessage(messages, messages.findIndex((item) => item.id === active.id), messages.findIndex((item) => item.id === over.id)));
  };

  return (
    <div className="composer-body">
      <label className="field macro-field">
        <span>用户输入（宏变量内容）</span>
        <textarea
          rows={2}
          value={macroValue}
          aria-label="用户输入（宏变量内容）"
          placeholder={`在这里输入内容，发送时将替换消息中的 ${macroName}`}
          onChange={(event) => onMacroValueChange(event.target.value)}
        />
        <small>发送请求时，消息里出现的 {macroName} 会被替换成上面的输入内容；留空则替换为空。</small>
      </label>
      <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={onDragEnd}>
        <SortableContext items={messages.map((message) => message.id)} strategy={verticalListSortingStrategy}>
          <div className="message-list">
            {messages.map((message, index) => (
              <MessageRow
                key={message.id}
                message={message}
                index={index}
                count={messages.length}
                onChange={(next) => onChange(messages.map((item) => item.id === next.id ? next : item))}
                onCopy={() => onChange(copyMessage(messages, message.id))}
                onDelete={() => onChange(removeMessage(messages, message.id))}
                onMove={(direction) => onChange(moveMessage(messages, index, index + direction))}
              />
            ))}
          </div>
        </SortableContext>
      </DndContext>
      <button className="secondary-button add-message" type="button" onClick={() => onChange(addMessage(messages))}>
        <Plus size={16} /> 添加消息
      </button>
    </div>
  );
}

// src/APP/调试台/components/MessageComposer.vue
<template>
  <div class="composer-body">
    <label class="field macro-field">
      <span>用户输入（宏变量内容）</span>
      <textarea
        rows="2"
        :value="macroValue"
        aria-label="用户输入（宏变量内容）"
        :placeholder="`在这里输入内容，发送时将替换消息中的 ${macroName}`"
        @input="onMacroInput"
      />
      <small>发送请求时，消息里出现的 {{ macroName }} 会被替换成上面的输入内容；留空则替换为空。</small>
    </label>
    <div class="message-list">
      <MessageRow
        v-for="(message, index) in messages"
        :key="message.id"
        :message="message"
        :index="index"
        :count="messages.length"
        @change="onMessageChange"
        @copy="onCopy(message)"
        @delete="onDelete(message)"
        @move="(direction) => onMove(message, index, direction)"
      />
    </div>
    <button class="secondary-button add-message" type="button" @click="onAdd">
      <i class="fas fa-plus" aria-hidden="true"></i> 添加消息
    </button>
  </div>
</template>

<script setup lang="ts">
import type { ChatMessage } from '../domain/chat';
import { addMessage, copyMessage, moveMessage, removeMessage } from '../domain/messages';
import MessageRow from './MessageRow.vue';

const props = defineProps<{
  messages: ChatMessage[];
  macroName: string;
  macroValue: string;
}>();

const emit = defineEmits<{
  (e: 'change', messages: ChatMessage[]): void;
  (e: 'macro-value-change', value: string): void;
}>();

function onMacroInput(event: Event) {
  emit('macro-value-change', (event.target as HTMLTextAreaElement).value);
}

function onMessageChange(next: ChatMessage) {
  emit('change', props.messages.map((item) => (item.id === next.id ? next : item)));
}

function onCopy(message: ChatMessage) {
  emit('change', copyMessage(props.messages, message.id));
}

function onDelete(message: ChatMessage) {
  emit('change', removeMessage(props.messages, message.id));
}

function onMove(message: ChatMessage, index: number, direction: number) {
  emit('change', moveMessage(props.messages, index, index + direction));
}

function onAdd() {
  emit('change', addMessage(props.messages));
}
</script>
